kortlek_map =  {"h1": ("pngKortlek/h1.png"),
			"h2": ("pngKortlek/h2.png"),
			"h3": ("pngKortlek/h3.png"),
			"h4": ("pngKortlek/h4.png"),
			"h5": ("pngKortlek/h5.png"),
			"h6": ("pngKortlek/h6.png"),
			"h7": ("pngKortlek/h7.png"),
			"h8": ("pngKortlek/h8.png"),
			"h9": ("pngKortlek/h9.png"),
			"h10": ("pngKortlek/h10.png"),
			"h11": ("pngKortlek/h11.png"),
			"h12": ("pngKortlek/h12.png"),
			"h13": ("pngKortlek/h13.png"),

			"c1": ("pngKortlek/c1.png"),
			"c2": ("pngKortlek/c2.png"),
			"c3": ("pngKortlek/c3.png"),
			"c4": ("pngKortlek/c4.png"),
			"c5": ("pngKortlek/c5.png"),
			"c6": ("pngKortlek/c6.png"),
			"c7": ("pngKortlek/c7.png"),
			"c8": ("pngKortlek/c8.png"),
			"c9": ("pngKortlek/c9.png"),
			"c10": ("pngKortlek/c10.png"),
			"c11": ("pngKortlek/c11.png"),
			"c12": ("pngKortlek/c12.png"),
			"c13": ("pngKortlek/c13.png"),

			"d1": ("pngKortlek/d1.png"),
			"d2": ("pngKortlek/d2.png"),
			"d3": ("pngKortlek/d3.png"),
			"d4": ("pngKortlek/d4.png"),
			"d5": ("pngKortlek/d5.png"),
			"d6": ("pngKortlek/d6.png"),
			"d7": ("pngKortlek/d7.png"),
			"d8": ("pngKortlek/d8.png"),
			"d9": ("pngKortlek/d9.png"),
			"d10": ("pngKortlek/d10.png"),
			"d11": ("pngKortlek/d11.png"),
			"d12": ("pngKortlek/d12.png"),
			"d13": ("pngKortlek/d13.png"),

			"s1": ("pngKortlek/s1.png"),
			"s2": ("pngKortlek/s2.png"),
			"s3": ("pngKortlek/s3.png"),
			"s4": ("pngKortlek/s4.png"),
			"s5": ("pngKortlek/s5.png"),
			"s6": ("pngKortlek/s6.png"),
			"s7": ("pngKortlek/s7.png"),
			"s8": ("pngKortlek/s8.png"),
			"s9": ("pngKortlek/s9.png"),
			"s10": ("pngKortlek/s10.png"),
			"s11": ("pngKortlek/s11.png"),
			"s12": ("pngKortlek/s12.png"),
			"s13": ("pngKortlek/s13.png"),

			"blank": ("pngKortlek/blank.png")}